### PR TITLE
Extracting patch files from results

### PR DESCRIPTION
**Pull request by zaricu22**

### CODE REVIEW

**Comment by tdurieux** [comment]
Thank you for your contribution, is your PR ready to be merged?

**Comment by zaricu22** [comment]
Yes.
I have updated Python script to correctly consider 'results.json' format of jGenProg, jKali, jMutRepair, and Cardumen.
Additionally, I provided 7z archive for purpose of data usage without running Python script.  
PR files are completely separated and they don't provide any kind of modification on existing files.

The only disagreement is that my script found 67.205 patches and your report has marked 67.211 patches.

**Comment by tdurieux** [comment]
Interesting that there are 6 patches missing. I don't really understand how it could happen.

**Comment by tdurieux** [comment]
Thank you for your contribution.

**Pull request merged**
